config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'
  get '/about', to: 'static#about'

  get '/parent_account', to: 'application#parent_account', as: 'parent_account'
  get '/teacher_account', to: 'application#teacher_account', as: 'teacher_account'

  get '/parents/login', to: 'parents#loginform', as: 'parent_login'
  post '/parents/login', to: 'parents#handle_login'
  # post '/logout', to: 'parents#logout'

  get '/teachers/login', to: 'teachers#loginform', as: 'teacher_login'
  post '/teachers/login', to: 'teachers#handle_login'
  
  #LOGOUT

  post '/logout', to: 'application#logout'

  post '/teachers/endorsements/:activity_id', to: 'teachers#endorse', as: 'teacher_endorse'
  
  #SESSIONS

  # get '/login', to: "sessions#new"
  # post '/login', to: "sessions#create"
  # post '/logout', to: "sessions#destroy"

  resources :teachers
  resources :ratings
  resources :parents
  resources :activities
  resources :endorsements

  get '*path' => redirect('/')



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :parent
    belongs_to :activity

    validates :num_rating, numericality: { 
        less_than_or_equal_to: 10,
        greater_than_or_equal_to: 0
      }

      validates :description, presence: true

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  
  before_action :check_if_logged_in
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  def index
    @ratings = @logged_in_user.ratings
  end

  def new
    @rating = Rating.new
    @errors = flash[:errors]
  end

  def create
    @rating = @logged_in_user.ratings.create(rating_params)
    if @rating.valid?
      redirect_to @rating.activity
    else
      flash[:errors] = @rating.errors.full_messages
      redirect_to @rating.activity
    end
  end

  def edit
  end
  
  def update
    @rating.update(rating_params)
    redirect_to @rating.activity
  end

  def destroy
    @rating.destroy
    redirect_to @rating
  end

  private

  def set_rating
    @rating = Rating.find(params[:id])
  end

  def rating_params
    params.require(:rating).permit(:parent_id, :activity_id, :num_rating, :description)
  end

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/edit.html.erb
<div class="card">
  
  <%= form_for @rating, html: { class: "form" } do |f| %>
    <h2 class="form-header">Edit Rating</h2>

    <%= f.label :num_rating %>
    <%= f.number_field :num_rating %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li class="error"><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.submit "Update Rating", class: "button" %>
  <% end %>

</div>

app/views/ratings/index.html.erb
<section class="profile">
  <div class="profile__info">

    <h1 class="display-6"> See Your Ratings </h1>

    <ul class="rating-list">
        <% @ratings.each do |rating| %>
            <li>
            You gave it a rating of: <%= rating.num_rating%> out of 10<br/>
            Description: <%= rating.description %><br/>
            <%= button_to "Edit Rating", edit_rating_path(rating), method: :get, class: "button" %>
            <%= button_to "Delete Rating", rating, method: :delete, class: "button" %>
            </li>
        <% end %>
    </ul>
<br/>
<%= button_to "Return To Your Profile", @logged_in_user, method: :get, class: "button" %> 

    </section>

app/views/ratings/new.html.erb
<div class="card"> 

<%= form_for @rating, html: { class: "form" } do |f| %>
    <h2 class = "form-header"> Write a rating </h2>

    <%= f.label :num_rating, "Submit your rating" %>
    <%= f.number_field :num_rating %> <br/><br/>

    <%= f.label :description, "Add a description"%>
    <%= f.text_field :description %><br/><br/>

    <% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |error_message| %>
            <li class = "error"> <%= error_message %> </li>
        <% end %>
    </ul>
    <% end %>

    <%= f.submit "Post Rating", class: "button" %>

<% end %>

<%# how to direct this back to the profile specific to the rating? 
link_to "Return to Activity Profile", activity_path(rating.activity_id) %>

</div>