config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'
  get '/about', to: 'static#about'

  get '/parent_account', to: 'application#parent_account', as: 'parent_account'
  get '/teacher_account', to: 'application#teacher_account', as: 'teacher_account'

  get '/parents/login', to: 'parents#loginform', as: 'parent_login'
  post '/parents/login', to: 'parents#handle_login'
  # post '/logout', to: 'parents#logout'

  get '/teachers/login', to: 'teachers#loginform', as: 'teacher_login'
  post '/teachers/login', to: 'teachers#handle_login'
  
  #LOGOUT

  post '/logout', to: 'application#logout'

  post '/teachers/endorsements/:activity_id', to: 'teachers#endorse', as: 'teacher_endorse'
  
  #SESSIONS

  # get '/login', to: "sessions#new"
  # post '/login', to: "sessions#create"
  # post '/logout', to: "sessions#destroy"

  resources :teachers
  resources :ratings
  resources :parents
  resources :activities
  resources :endorsements

  get '*path' => redirect('/')



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
    belongs_to :teacher
    belongs_to :activity
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  
  before_action :check_if_logged_in
  before_action :set_endorsement, only: [:show, :edit, :update, :destroy]

  def index
    @endorsements = @logged_in_user.endorsements
  end

  def new
    @endorsement = Endorsement.new
  end

  def create
    @endorsement = Endorsement.create(endorsement_params)
    if endorsement.valid?
      redirect_to @endorsement.teacher
    else
      flash[:errors] = endorsement.errors.full_messages
      redirect_to new_endorsement_path
    end
  end

  def edit
  end

  def update
    @endorsement.update(endorsement_params)
    redirect_to @endorsement
  end

  def show
  end

  def destroy
    @endorsement.destroy
    redirect_to @endorsement
  end

  private 

  def set_endorsement
    @endorsement = Endorsement.find(params[:id])
  end

  def endorsement_params
    params.require(:endorsement).permit(:activity_id, :teacher_id, :list_category)
  end

end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/views/endorsements/edit.html.erb
<h1>Endorsements#edit</h1>
<p>Find me in app/views/endorsements/edit.html.erb</p>

<% if logged_in? %>
        Welcome, <%= logged_in_user.username %>!
        <%= button_to "Log out", "/logout" %>
      <% else %>
        <%= link_to "Log In", parent_login_path %>
      <% end %>

app/views/endorsements/index.html.erb
<h1> Your Endorsements </h1>

    <ul class="activity-list">
        <% @endorsements.each do |endorsement| %>
            <li class="activity-list__item">
                <div class="activity-list__info">
                    <%= link_to endorsement.activity.name, endorsement.activity, class: "activity-list__name"%>
                    <div class="activity-list__organization">
                        <%= endorsement.activity.organization.name %> at <%= endorsement.activity.organization.city %>, <%=endorsement.activity.organization.state %>
                    </div>
                    <%= button_to "Delete Endorsement", endorsement, method: :delete, class: "button" %>
                </div>
            </li>
        <% end %>
    </ul>

app/views/endorsements/new.html.erb
<h1>Endorsements#new</h1>
<p>Find me in app/views/endorsements/new.html.erb</p>