config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'
  get '/about', to: 'static#about'

  get '/parent_account', to: 'application#parent_account', as: 'parent_account'
  get '/teacher_account', to: 'application#teacher_account', as: 'teacher_account'

  get '/parents/login', to: 'parents#loginform', as: 'parent_login'
  post '/parents/login', to: 'parents#handle_login'
  # post '/logout', to: 'parents#logout'

  get '/teachers/login', to: 'teachers#loginform', as: 'teacher_login'
  post '/teachers/login', to: 'teachers#handle_login'
  
  #LOGOUT

  post '/logout', to: 'application#logout'

  post '/teachers/endorsements/:activity_id', to: 'teachers#endorse', as: 'teacher_endorse'
  
  #SESSIONS

  # get '/login', to: "sessions#new"
  # post '/login', to: "sessions#create"
  # post '/logout', to: "sessions#destroy"

  resources :teachers
  resources :ratings
  resources :parents
  resources :activities
  resources :endorsements

  get '*path' => redirect('/')



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parent.rb
class Parent < ApplicationRecord
    has_many :ratings
    has_many :activities, through: :ratings
    belongs_to :zipcode

    has_secure_password

    validates :email, presence: true, uniqueness: { message: "Someone has already used this email address." }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "There's something funky with your email address!" },  length: {maximum: 75}    
    
    validates :username, presence: true
    
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  
  before_action :set_parent, only: [:show, :edit, :update]
  before_action :check_if_logged_in, only: [:show, :edit, :index, :update]
  skip_before_action :check_if_logged_in, only: [:loginform, :handle_login, :new, :create]


  def index
    @parents = Parent.all
  end

  def show
    if @logged_in_user.id != params[:id].to_i
      redirect_to @logged_in_user
    end
  end

  def new
    @parent = Parent.new
    @errors = flash[:errors]
  end

  def create
    @num = params[:parent][:zipcode]
    @zipcode = Zipcode.find_or_create_by!(zip_num: @num)
    params[:parent][:zipcode_id] = @zipcode.id
    @parent = Parent.create(parent_params)
    if @parent.valid?
      session[:parent_id] = @parent.id
      redirect_to @parent
    else
      flash[:errors] = @parent.errors.full_messages
      redirect_to new_parent_path
    end
  end

  def edit
  end

  def update
    @parent.update(parent_params)
    redirect_to @parent
  end

  def loginform
    @errors = flash[:errors]
    # render "teachers/login"
  end

  def handle_login
    @parent = Parent.find_by(email: params[:email])
    if @parent && @parent.authenticate(params[:password])
      session[:parent_id] = @parent.id
      redirect_to @parent
    else
      flash[:error] = "Invalid email or password"
      redirect_to parent_login_path
    end
  end

  def logout
    session[:parent_id] = nil
    redirect_to root_path
  end

  private

  def set_parent
    @parent = Parent.find(params[:id])
  end

  def parent_params
    params.require(:parent).permit(:username, :password, :email, :zipcode_id)
  end

end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/edit.html.erb
<div class="card">
  
  <%= form_for @parent, html: { class: "form" } do |f| %>
    <h2 class="form-header">Edit Profile</h2>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    
    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.label :zipcode_id %>
    <%= f.number_field :zipcode_id %>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li class="error"><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.submit "Update Your Information", class: "button" %>
  <% end %>

</div>

app/views/parents/index.html.erb
<section class="container">

<h1 class="form-label"> Use the search options above to find an activity! </h1>

</section>

app/views/parents/loginform.html.erb
<div class="card">

<%= form_tag url:"/parents/login", method: "POST", class: 'form' do %>
  <h2 class="form-header">Parent Login</h2>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <br/><br/>
  <%= label_tag :password %>
  <%= password_field_tag :password, class: "block" %>
  <%= submit_tag "Log In", class: "button" %>

  <br/>

  <% if flash[:error] %>
    <ul>
        <li class="error"><%= flash[:error] %></li>
    </ul>
  <% end %>
<br/>

<% end %>

<%# <%= render "teachers/login" %>

app/views/parents/new.html.erb
<section class="section">
			<div class="container grid">
				<nav class="breadcrumb" aria-label="breadcrumbs">
					<ul>
						<li><a href="/">Home</a></li>
						<li class="is-active"><a href="#" aria-current="page">Sign up for Acorn</a></li>
					</ul>
				</nav>
			</div>
		</section>

<style>
.grid {
	display: grid;
	grid-template-columns: 1fr 624px 1r;
}

.grid * { grid-column: 2 / 3; }
</style>

<div class="field grid"> 
  <h1 class="title">Parent Signup</h1>
  <%= form_for @parent, html: { class: "field" } do |f| %>
    <label class="label"><%= f.label :email %></label>
    <input class="input is-success" f.text_field :email placeholder="hello@example.com">
    <label class="label"><%= f.label :username %></label>
    <input class="input is-success" f.text_field :username placeholder="@barbarastreisand">
    <label class="label"><%= f.label :password %></label>  
    <input class="input" f.password_field :password placeholder="**********">
    <label class="label"><%= f.label :zipcode %></label>
    <input class="input" f.text_field :zipcode placeholder="10011">

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li class="error"><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="field">
      <div class="control">
        <label class="checkbox">
          <input type="checkbox">
            I agree to the <a href="#">terms and conditions</a>
        </label>
      </div>
  </div>

    <%= submit_tag "Signup" %>
  <% end %>
</div>

app/views/parents/show.html.erb
<section class="profile">
  <div class="profile__info">

    <h3 class="display-15">Your Profile</h3>

    <h4 class="form-label"> Email: <%= @parent.email%> <br/><br/>
    Username: <%= @parent.username %> <br/><br/>
    Zipcode: <%= @parent.zipcode.zip_num %> </h4>
<br/><br/>

  <div>
    <h3 class="display-15">Your Ratings</h3>
    <% if @parent.ratings.length == 0 %>
      <p>You have not rated any activities yet</p>
    <% else %>
        <%= button_to "See Your Ratings", ratings_path, method: :get, class: "btn btn-outline-dark"%>
    <% end %>
    <br/>
</div>
 </div>
 <div>
  <%= button_to "Edit Your Profile", edit_parent_path, method: :get, class: "button" %>
</div>
</section>