config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'
  get '/about', to: 'static#about'

  get '/parent_account', to: 'application#parent_account', as: 'parent_account'
  get '/teacher_account', to: 'application#teacher_account', as: 'teacher_account'

  get '/parents/login', to: 'parents#loginform', as: 'parent_login'
  post '/parents/login', to: 'parents#handle_login'
  # post '/logout', to: 'parents#logout'

  get '/teachers/login', to: 'teachers#loginform', as: 'teacher_login'
  post '/teachers/login', to: 'teachers#handle_login'
  
  #LOGOUT

  post '/logout', to: 'application#logout'

  post '/teachers/endorsements/:activity_id', to: 'teachers#endorse', as: 'teacher_endorse'
  
  #SESSIONS

  # get '/login', to: "sessions#new"
  # post '/login', to: "sessions#create"
  # post '/logout', to: "sessions#destroy"

  resources :teachers
  resources :ratings
  resources :parents
  resources :activities
  resources :endorsements

  get '*path' => redirect('/')



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :ratings
    has_many :endorsements
    has_many :parents, through: :ratings
    has_many :teachers, through: :endorsements
    belongs_to :organization
    belongs_to :zipcode

    def average_rating
        total = self.ratings.sum do |rating|
            rating.num_rating
        end
        if self.ratings.length == 0
            return 0
        else
            average = (total / self.ratings.length).to_f
        end
    end

    def self.search_by_activity(search)
        if search
            activity_keyword = Activity.find_by(name: search)
            if activity_keyword
                self.where(activity_id: activity_keyword)
            else
                @activities = Activity.all
            end
            @activities = Activity.all
        end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
    belongs_to :teacher
    belongs_to :activity
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :activities
    belongs_to :zipcode
end

app/models/parent.rb
class Parent < ApplicationRecord
    has_many :ratings
    has_many :activities, through: :ratings
    belongs_to :zipcode

    has_secure_password

    validates :email, presence: true, uniqueness: { message: "Someone has already used this email address." }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "There's something funky with your email address!" },  length: {maximum: 75}    
    
    validates :username, presence: true
    
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :parent
    belongs_to :activity

    validates :num_rating, numericality: { 
        less_than_or_equal_to: 10,
        greater_than_or_equal_to: 0
      }

      validates :description, presence: true

end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :endorsements
    has_many :activities, through: :endorsements
    belongs_to :zipcode

    has_secure_password
    
    validates :email, presence: true, uniqueness: { message: "Someone has already used this email address." }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "There's something funky with your email address!" },  length: {maximum: 75}
    
end

app/models/zipcode.rb
class Zipcode < ApplicationRecord
    has_many :parents 
    has_many :teachers
    has_many :organizations 
    has_many :activities
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  
  before_action :set_parent, only: [:show, :edit, :update]
  before_action :check_if_logged_in, only: [:show, :edit, :index, :update]
  skip_before_action :check_if_logged_in, only: [:loginform, :handle_login, :new, :create]


  def index
    @parents = Parent.all
  end

  def show
    if @logged_in_user.id != params[:id].to_i
      redirect_to @logged_in_user
    end
  end

  def new
    @parent = Parent.new
    @errors = flash[:errors]
  end

  def create
    @num = params[:parent][:zipcode]
    @zipcode = Zipcode.find_or_create_by!(zip_num: @num)
    params[:parent][:zipcode_id] = @zipcode.id
    @parent = Parent.create(parent_params)
    if @parent.valid?
      session[:parent_id] = @parent.id
      redirect_to @parent
    else
      flash[:errors] = @parent.errors.full_messages
      redirect_to new_parent_path
    end
  end

  def edit
  end

  def update
    @parent.update(parent_params)
    redirect_to @parent
  end

  def loginform
    @errors = flash[:errors]
    # render "teachers/login"
  end

  def handle_login
    @parent = Parent.find_by(email: params[:email])
    if @parent && @parent.authenticate(params[:password])
      session[:parent_id] = @parent.id
      redirect_to @parent
    else
      flash[:error] = "Invalid email or password"
      redirect_to parent_login_path
    end
  end

  def logout
    session[:parent_id] = nil
    redirect_to root_path
  end

  private

  def set_parent
    @parent = Parent.find(params[:id])
  end

  def parent_params
    params.require(:parent).permit(:username, :password, :email, :zipcode_id)
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  
  before_action :check_if_logged_in
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  def index
    @ratings = @logged_in_user.ratings
  end

  def new
    @rating = Rating.new
    @errors = flash[:errors]
  end

  def create
    @rating = @logged_in_user.ratings.create(rating_params)
    if @rating.valid?
      redirect_to @rating.activity
    else
      flash[:errors] = @rating.errors.full_messages
      redirect_to @rating.activity
    end
  end

  def edit
  end
  
  def update
    @rating.update(rating_params)
    redirect_to @rating.activity
  end

  def destroy
    @rating.destroy
    redirect_to @rating
  end

  private

  def set_rating
    @rating = Rating.find(params[:id])
  end

  def rating_params
    params.require(:rating).permit(:parent_id, :activity_id, :num_rating, :description)
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def home
    if logged_in?
      if cookies[:parent_account]
        redirect_to parent_path(logged_in_user)
      else
        redirect_to teacher_path(logged_in_user)
      end
    end
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="starter-template.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Acorn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <header class="menu">
          <nav class="navbar navbar-expand-lg navbar-light bg-light new-nav-color">
            <a class="navbar-brand"><img src="https://live.staticflickr.com/65535/49782057128_8845590be4_z.jpg" width="75" height="65" alt="Acorn">Acorn</a>
          <div class="right inline">
            <button class="button"><%= link_to "Home", root_path %></button>
            <button class="button"><%= link_to "About", "/about" %></button>
              <% if logged_in? %>
                <button class="button"><%= link_to "Search For An Activity", activities_path, class: "item" %></button>
                <button class="button"><%= link_to "Find A Teacher", teachers_path, class: "item" %></button>
                <% if logged_in_parent %>
                    <button class="button"><%= link_to "See My Ratings", ratings_path, class: "item" %></button>
                <% end %>
                <% if logged_in_teacher %>
                    <button class="button"><%= link_to "See My Endorsements", endorsements_path, class: "item" %></button>
                <% end %>
                  <span class="item">      
                      <% if logged_in? %>
                        Welcome, <%= logged_in_user.username %>!
                      <%= button_to "Log out", "/logout" %>
                      <% end %>
                  </span>
                <% else %>
                  <div class="dropdown right inline">
                    <button class="button dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Parents
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href='parents/new'>Signup as a parent</a>
                      <a class="dropdown-item" href='parents/login'>Login as a parent</a>
                    </div>
                  </div>
                    <div class="dropdown right inline">
                      <button class="button dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Teachers
                      </button>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href= 'teachers/new'>Signup as a teacher</a>
                      <a class="dropdown-item" href="teachers/login">Login as a teacher</a>
                    </div>
                  </div>
                <% end %>
              </nav>
          </header>
        <main>
          <div class="container">
              <%= yield %>
        </div>
      </main>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

app/views/layouts/template.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>

  
    <% if logged_in? %>
        Welcome, <%= logged_in_user.username %>!
        <%= button_to "Log out", "/logout" %>
      <% else %>
        <%= link_to "Log In", parent_login_path %>
      <% end %>


  <section class="section">
    <div class="container">
      <h1 class="title">
        Hello World
      </h1>
      <p class="subtitle">
        My first website with <strong>Bulma</strong>!
      </p>
    </div>
  </section>
  </body>
</html>